### ISSUE TITLE
Operation in context of conflict

### ISSUE THREAD

**Issue by guibou** [idursun/jjui#48]
I do have issues with `jjui` when conflict (on revision) happen.

I'm using latest jjui, 0.8.3.

First, similarly to what's decribe in #27, so maybe a regression, when doing preview of a conflicted revision, `jjui` show the conflict and ambiguity and refuses to display me the change, see:

![Image](https://github.com/user-attachments/assets/155b0a3c-cc06-4a48-a5ce-bd033c19a81c)

In this context, I think that `jjui` should use the commit id instead of the revision id.

However, I observed a more problematic issue.

Consider the following repository:

```
@  vsqzquzt?? guillaum.bouchard@gmail.com 2025-04-07 10:31:16 7e018a53
│  (empty) This is description 1
│ ○  vsqzquzt?? guillaum.bouchard@gmail.com 2025-04-07 10:31:17 47dbc207
├─╯  (empty) This is descrition 2
○  umtnrxvl guillaum.bouchard@gmail.com 2025-04-07 10:30:43 git_head() 54c41233
│  Add a file
◆  zzzzzzzz root() 00000000
```

For the record, I've obtained it by doing two `D`escription update simultaneously, then validating the first one, then the second one.

In `jj ui`, if I `a`bandon one of the two conflicting revision, the UI claims that it used `jj abandon -r v` and I ends with the following log:

```
@  sowopuyt guillaum.bouchard@gmail.com 2025-04-07 10:38:27 add57a18
│  (empty) (no description set)
○  umtnrxvl guillaum.bouchard@gmail.com 2025-04-07 10:30:43 git_head() 54c41233
│  Add a file
◆  zzzzzzzz root() 00000000
```

As you can see, it completly abandon both revision `v`.

However, `jj abandon -r v` complains:

```
jj abandon -r v
Abandoned the following commits:
  vsqzquzt?? 47dbc207 (empty) This is descrition 2
  vsqzquzt?? 7e018a53 (empty) This is description 1
Working copy now at: krnkmlvy 13be8c4c (empty) (no description set)
Parent commit      : umtnrxvl 54c41233 Add a file
```

From my PoV, `jjui` should complain about the ambiguity and refuses to abandon all commits matching this revision.

So similarly, the abandon should either use the explicit commit id OR fails with a notice.

**Comment by idursun** [comment]
oh geez, I totally forgot that conflicted ids have a different structure. I fixed this now and added a test case too. Sorry for the inconvenience.

**Comment by guibou** [comment]
@idursun thank you for the fast reaction.

However, I'm wondering about what you've fixed. Unless I've made a mistake in the way I build and not included the commit, but:

- `a`bandon on a conflict still abandon all the other revisions without error message.
- `P` on a conflicted revision still show the error message

**Comment by idursun** [comment]
Oh, I see. I fixed conflicted revisions for the short id case ( e.g. p?? ), but I can see now that it doesn't work with the long ids. (e.g. pusvoztl??). 

I fixed it for the latter case now.

Regarding `jj abandon`; I believe that's the default behaviour of `jj`.  When I run `jj abandon -r p` from the command line, I can see it is abandoning all of them. (and there's no error message either).

I believe `jjui` should stick to the default behaviour of commands.

**Comment by guibou** [comment]
Thank you.

I confirm that `jj abandon` works as you described (and that I exactly depicted that in my description above, so looks like my brain had read what I wanted to read and not what was on my terminal... Really sorry about that).

**Comment by idursun** [comment]
No worries! I see you created a separate issue for the `abandon` behaviour. I guess we can close this one then.

**Comment by guibou** [comment]
I'm really sorry, there is a weird special case.

Looks like that the "conflicted commit", if it is currently the one edited, still does not works correctly.

See for yourself, here I'm editing the commit "This is description 1":

![Image](https://github.com/user-attachments/assets/b4f1cceb-c006-4964-b23f-18a18ca2f4cb)

You can see that one does have the conflicting `P` panel, when the other one is fine.

If now I edit "This is description 2":

![Image](https://github.com/user-attachments/assets/10d34b1b-63ea-4c4e-b9c6-139f76e8f410)

If now I edit a commit on top, no problem:

![Image](https://github.com/user-attachments/assets/d95930c3-01de-43a2-acf4-fba88f469527)

I'm so sorry, this things seems to be a rabbit hole.

**Comment by idursun** [comment]
I think this is happening because the first change id has 3 parts (colourwise) short, rest and then `??`. I will make a change, I hope it handles that case.
